services:
  app:
    build:
      context: .
    ports:
      - "8086:8086"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - DB_SERVER=legallinx-postgres-db:5432
      - DB_NAME=ccw_fees
      - DB_USER=postgres
      - DB_PASSWORD=example
    networks:
      - legallinx-network

networks:
  legallinx-network:
    name: legallinx-network
    external: true
